export class CriarApostaCash{
    id: string;
    descricaoAposta : string;
    resposta1 : string;
    resposta2 : string;
    resposta3 : string;
    resposta4 : string;
    resposta5 : string;
    resposta6 : string;
    resposta7 : string;
    resposta8 : string;
    resposta9 : string;
    resposta10 : string;
    v1 : string;
    v2 : string;
    v3 : string;
    v4 : string;
    v5 : string;
    v6 : string;
    v7 : string;
    v8 : string;
    v9 : string;
    v10 : string;
    respostaCorreta1 : string;
    respostaCorreta2 : string;
    respostaCorreta3 : string;
    dataCriado : string;
    dataTermino : string;
    status : string;
    nome: string;
    email:string;
    imagem1:string;
    imagem2:string;
    imagem3:string;
    cardT:string;
    cardR:string;
    categoria:string;
    vFixo:string;
    constructor(){}

    setDados(obj : any){
        this.descricaoAposta = obj.descricaoAposta;
        this.resposta1 = obj.resposta1;
        this.resposta2 = obj.resposta2;
        this.resposta3 = obj.resposta3;
        this.resposta4 = obj.resposta4;
        this.resposta5 = obj.resposta5;
        this.resposta6 = obj.resposta6;
        this.resposta7 = obj.resposta7;
        this.resposta8 = obj.resposta8;
        this.resposta9 = obj.resposta9;
        this.resposta10 = obj.resposta10;
        this.v1 = obj.v1;
        this.v2 = obj.v2;
        this.v3 = obj.v3;
        this.v4 = obj.v4;
        this.v5 = obj.v5;
        this.v6 = obj.v6;
        this.v7 = obj.v7;
        this.v8 = obj.v8;
        this.v9 = obj.v9;
        this.v10 = obj.v10;
        this.respostaCorreta1 = obj.respostaCorreta1;
        this.respostaCorreta2 = obj.respostaCorreta2;
        this.respostaCorreta3 = obj.respostaCorreta3;
        this.dataCriado = obj.dataCriado;
        this.dataTermino = obj.dataTermino;
        this.status = obj.status;
        this.nome = obj.nome;
        this.email = obj.email;
        this.imagem1 = obj.imagem1;
        this.imagem2 = obj.imagem2;
        this.imagem3 = obj.imagem3;
        this.cardT = obj.cardT;
        this.cardR = obj.cardR;
        this.categoria = obj.categoria;
        this.vFixo = obj.vFixo;
    }
}